### ISSUE TITLE
Jupyter notebook import scanpy.api 

### ISSUE THREAD

**Issue by TamaraO** [scverse/scanpy#160]
I have followed these instructions to install scanpy into my miniconda environment:
[](https://scanpy.readthedocs.io/en/latest/installation.html)

Whether I try to import scanpy straight from terminal, it keeps giving me an error:
```
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 23:12:44)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scanpy.api as sc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/scanpy/__init__.py", line 24, in <module>
    import anndata
  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData, _MAIN_NARRATIVE
  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/anndata/base.py", line 287
    return f'Backing file manager of file {self._filename}.'
                                                           ^
SyntaxError: invalid syntax
>>>
```

I also get the error when I try to use it with jupyter notebook:

```
import scanpy.api as sc

Traceback (most recent call last):

  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-4a13c503728c>", line 1, in <module>
    import scanpy.api as sc

  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/scanpy/__init__.py", line 24, in <module>
    import anndata

  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData, _MAIN_NARRATIVE

  File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/anndata/base.py", line 287
    return f'Backing file manager of file {self._filename}.'
                                                           ^
SyntaxError: invalid syntax
```

What is the issue? How can I get over this? 

Thank you!

**Comment by flying-sheep** [comment]
Hi! Thanks for using scanpy!

The error is in [`anndata`](https://github.com/theislab/anndata) so filing a bug there would be more fitting. I did it for you: https://github.com/theislab/anndata/issues/23

---

Lastly, please do ```` ```pytb ```` for your python tracebacks blocks so we get syntax highlighting:

> ````markdown
> I also get the error when I try to use it with jupyter notebook:
> 
> ```pytb
> import scanpy.api as sc
> 
> Traceback (most recent call last):
> 
>   File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-> packages/IPython/core/interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   […]
> 
> SyntaxError: invalid syntax
> ```
> ````

This would look like this:

> I also get the error when I try to use it with jupyter notebook:
> 
> ```pytb
> import scanpy.api as sc
> 
> Traceback (most recent call last):
> 
>   File "/home/unix/tamarao/miniconda3/envs/tamara_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   […]
> 
> SyntaxError: invalid syntax
> ```

**Comment by flying-sheep** [comment]
fixed in https://github.com/theislab/anndata/commit/555c15c8a170944b762ba7ce1d8c0b41f4e4dfbe

the fix should be in the next anndata release (0.6.2 or 0.7)

**Comment by TamaraO** [comment]
Thank you for the prompt response! I did not install anndata separately, I just followed instructions from https://scanpy.readthedocs.io/en/latest/installation.html to install scanpy using `pip install scanpy` in miniconda environment. Do I need to reinstall another version of anndata? Or of scanpy? Sorry, still not sure how to fix this. Thank you!

**Comment by flying-sheep** [comment]
yeah, this was fixed inside of anndata, so you need to update anndata, not scanpy.

`pip install anndata~=0.6.4` should get you a version where this is fixed! 😄

**Comment by TamaraO** [comment]
Perfect! That fixed it! Thanks a lot!
