### ISSUE TITLE
sc.tl.umap error with init_pos="paga"

### ISSUE THREAD

**Issue by graddi** [scverse/scanpy#769]
Hello,

Trying to use sc.tl.umap with initial positions from sc.tl.paga. Seems an error with UMAP from the error log. But it is only called when calling paga positions, UMAP works otherwise.

I do see https://github.com/theislab/scanpy/issues/666, and https://github.com/lmcinnes/umap/pull/262, but I am already running scanpy 1.4.4 and umap 0.3.9 so I don't understand how to solve the issue?

Attached error. Any suggestions? 
Thanks!

<img width="575" alt="Screen Shot 2019-08-05 at 19 02 18" src="https://user-images.githubusercontent.com/20108378/62485139-c560df80-b7b3-11e9-8333-7e511c263a79.png">

**Comment by jipeifeng** [comment]
I have also got exactly the same error !

**Comment by ivirshup** [comment]
There hasn't actually been a release of UMAP since the pull request that should fix this (https://github.com/lmcinnes/umap/pull/261). I think I see what happened here, so I've opened a PR to fix it here.

For now, this can be worked around by running:

```python
sc.tl.umap(adata, init_pos=sc.tl._utils.get_init_pos_from_paga(adata))
```

**Comment by graddi** [comment]
Hello @ivirshup thanks for this!

Quick question (still very new to python). Upon following your suggestion I get this error:
AttributeError: module 'scanpy.api.tl' has no attribute '_utils'

I then proceeded to install utils (pip install utils), and then
import utils

But still doesn't work. I assume it's because I'm not loading it correctly into the environment for scanpy to use but I don't know how?

**Comment by ivirshup** [comment]
No worries!

How did you import scanpy? It should be done like: `import scanpy as sc`, but I think you might have used the older method: `import scanpy.api as sc`.

**Comment by graddi** [comment]
Thanks again @ivirshup, that was indeed the issue for the first part! Now building the umap works, however plotting still does not! 

I tried both:
sc.pl.umap(gr_all_sce_copy, init_pos='paga', color=['clust_types'])

and 

sc.pl.umap(gr_all_sce_copy, init_pos=sc.tl._utils.get_init_pos_from_paga(gr_all_sce_copy), color=['clust_types'])

But I get the same error:
<img width="506" alt="Screen Shot 2019-08-07 at 13 08 55" src="https://user-images.githubusercontent.com/20108378/62622038-47b4e500-b915-11e9-9a7d-345491f19da5.png">

Please note that output of 
sc.tl.umap(gr_all_sce_copy, init_pos=sc.tl._utils.get_init_pos_from_paga(gr_all_sce_copy))

is a bit weird as it seems to still add data to adata even though I use an object with a different name?
computing UMAP
    finished: added
    'X_umap', UMAP coordinates (adata.obsm) (0:00:14)

Thanks again for all the help!

**Comment by graddi** [comment]
Thank you very much that was the issue!

**Comment by lengfei5** [comment]
I got the same error with scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.3 scipy==1.3.2 pandas==0.25.3 scikit-learn==0.21.3 statsmodels==0.10.2 python-igraph==0.7.1 louvain==0.6.1
But I am so glad to find answer here and thanks a lot.
